### ISSUE TITLE
How to run (for non-Elm folk)?

### ISSUE THREAD

**Issue by scherrey** [myrho/dive-svg#1]
Definitely interested in the Dive-SVG app but, for those of us who don't know elm, how do we get this thing installed and running? Apologies for the uber noob question but the solution eludes me and I'm pretty certain I'm missing something that will result in a forehead slap when I learn what it is. I do have elm installed fwiw.

**Comment by myrho** [comment]
Hi scherrey,
thanks for your interest! Perhaps this [Web tool](https://myrho.github.io/dive-svg/) is what you are looking for?

**Comment by myrho** [comment]
I also added installation instructions now
